version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    depends_on:
      - express-server

  express-server:
    build:
      context: .
      dockerfile: Dockerfile.express
    ports:
      - "5000:5000"
