# Wybierz obraz bazowy z Node.js
FROM node:14

# Ustaw katalog roboczy w kontenerze
WORKDIR /app

# Skopiuj pliki z serwera do kontenera
COPY package*.json ./
COPY server.js ./

# Zainstaluj zależności
RUN npm install

# Wykonaj polecenie startowe serwera
CMD ["node", "server.js"]
